const { Server } = require("socket.io");
const express = require("express");
const cors = require("cors");
const pool = require("./db");
const http = require("http");
const { processRestockNotifications } = require("./services/notifyService");
const app = express();
app.use(cors());
app.use(express.json());
const PORT = 3000;

const server = http.createServer(app);
const io = new Server(server, {
  cors: {
    origin: "*", // tighten later
  },
});
io.on("connection", (socket) => {
  console.log("Client connected:", socket.id);

  socket.on("disconnect", () => {
    console.log("Client disconnected:", socket.id);
  });
});

app.get("/", (req, res) => {
  res.json({
    message: "Health OK",
  });
});

app.get("/products", async (req, res) => {
  try {
    console.log("pool", pool);
    const result = await pool.query("SELECT * FROM inventory");
    res.json(result.rows);
  } catch (err) {
    console.error(err.message);
    res.status(500).send("Server Error");
  }
});

app.post("/add", async (req, res) => {
  const { item_name, stock_count, price, category, image_url } = req.body;
  // Basic validation to ensure we don't send nulls to RDS
  if (!item_name || stock_count === undefined || !price || !category) {
    return res
      .status(400)
      .json({ error: "Please provide item_name, stock_count, and price" });
  }

  try {
    const query = `
      INSERT INTO inventory (item_name, stock_count, price, category, image_url) 
      VALUES ($1, $2, $3, $4, $5) 
      RETURNING *;
    `;
    const values = [item_name, stock_count, price, category, image_url];

    const result = await pool.query(query, values);

    // Return the newly created product (including the ID generated by RDS)
    res.status(201).json({
      message: "Product added successfully",
      product: result.rows[0],
    });
  } catch (err) {
    console.error("Database Error:", err.message);
    res.status(500).json({
      error: "Server error while adding product",
      message: err.message,
    });
  }
});

app.post("/products/update", async (req, res) => {
  try {
    const { id, price, stock_count, item_name, category, image_url } = req.body;

    if (!id) {
      return res.status(400).json({ message: "Product ID is required" });
    }
    const query = `
  UPDATE inventory
  SET 
    price = $1,
    stock_count = $2,
    item_name = $3,
    category = $4,
    image_url = $5,
    updated_at = NOW()
  WHERE id = $6
  RETURNING *;
`;

    const values = [price, stock_count, item_name, category, image_url, id];

    // check stock_count is 0 before triggering notification service

    const stock_check_query = `select * from inventory where id = $1`;
    const stock_check_result = await pool.query(stock_check_query, [id]);

    if (stock_check_result.rows[0].stock_count === 0 && stock_count > 0) {
      processRestockNotifications(id, item_name, price);
    }
    const result = await pool.query(query, values);

    if (result.rowCount === 0) {
      return res.status(404).json({ message: "Product not found" });
    }

    return res.status(200).json({
      message: "Product updated successfully",
      product: result.rows[0],
    });
  } catch (error) {
    console.error("Update product error:", error);
    res.status(500).json({ message: "Internal server error", error });
  }
});
app.post("/reserve", async (req, res) => {
  const { customer_name, phone, email, items, total_price, user_name } =
    req.body;
  console.log("payload", req.body);
  if (!customer_name || !email || !items || items.length === 0) {
    return res.status(400).json({ error: "Invalid payload" });
  }
  const client = await pool.connect();
  console.log("client======>", client);
  try {
    await client.query("BEGIN");
    const productIds = items.map((i) => i.productId);
    console.log("productIds", productIds);
    // 🔒 Lock all required products
    const productsResult = await client.query(
      `SELECT * FROM inventory 
       WHERE id = ANY($1)
       FOR UPDATE NOWAIT`,
      [productIds],
    );

    console.log("productsResult", productsResult);
    const products = productsResult.rows;

    // Validate stock
    for (let item of items) {
      const product = products.find((p) => p.id === item.productId);

      if (!product) {
        throw new Error(`Product not found: ${item.productId}`);
      }

      if (product.stock_count < item.quantity) {
        throw new Error(`Out of stock for ${product.item_name}`);
      }
    }

    // 🧾 Insert order
    const orderResult = await client.query(
      `INSERT INTO orders (customer_name, email, phone, status, total_amount, user_name)
       VALUES ($1, $2, $3, 'order_placed', $4, $5)
       RETURNING id`,
      [customer_name, email, phone, total_price, user_name],
    );

    console.log("order result", orderResult);
    const orderId = orderResult.rows[0].id;

    // 📦 Insert order items + update inventory
    for (let item of items) {
      const product = products.find((p) => p.id === item.productId);

      // Insert order item
      await client.query(
        `INSERT INTO order_items 
         (order_id, product_id, quantity, price_at_purchase)
         VALUES ($1, $2, $3, $4)`,
        [orderId, item.productId, item.quantity, product.price],
      );

      // Update inventory
      const updated = await client.query(
        `UPDATE inventory
         SET stock_count = stock_count - $1,
             updated_at = CURRENT_TIMESTAMP
         WHERE id = $2
         RETURNING id, stock_count`,
        [item.quantity, item.productId],
      );

      console.log("updated items", updated);
      // 🔥 Emit per product update
      io.emit("inventory:update", {
        productId: updated.rows[0].id,
        stock_count: updated.rows[0].stock_count,
      });
    }

    await client.query("COMMIT");

    return res.json({
      success: true,
      orderId,
    });
  } catch (err) {
    console.error("Reserve Error:", err.message);
    await client.query("ROLLBACK");
    return res.status(500).json({
      success: false,
      message: "Internal server error",
    });
  } finally {
    client.release();
  }
});

app.get("/orders", async (req, res) => {
  try {
    const result = await pool.query(
      "SELECT * from orders order by created_at desc",
    );
    res.json(result.rows);
  } catch (error) {
    console.error(error.message);
    res.status(500).send("Something went wrong");
  }
});

app.get("/orders/:orderId", async (req, res) => {
  const { orderId } = req.params;

  try {
    const query = `
      SELECT 
        o.id AS order_id,
        o.customer_name,
        o.email,
        o.phone,
        o.status,
        o.total_amount,
        o.created_at,

        oi.product_id,
        oi.quantity,

        i.item_name,
        i.image_url,
        i.price

      FROM orders o
      JOIN order_items oi ON o.id = oi.order_id
      JOIN inventory i ON oi.product_id = i.id

      WHERE o.id = $1
    `;

    const result = await pool.query(query, [orderId]);

    if (result.rows.length === 0) {
      return res.status(404).json({ error: "Order not found" });
    }

    // 🧠 Transform flat rows → structured object
    const order = {
      order_id: result.rows[0].order_id,
      customer_name: result.rows[0].customer_name,
      email: result.rows[0].email,
      phone: result.rows[0].phone,
      status: result.rows[0].status,
      total_price: result.rows[0].total_amount,
      created_at: result.rows[0].created_at,
      items: [],
    };

    order.items = result.rows.map((row) => ({
      product_id: row.product_id,
      item_name: row.item_name,
      image_url: row.image_url,
      price: row.price,
      quantity: row.quantity,
    }));

    res.json(order);
  } catch (err) {
    console.error("Error fetching order details:", err.message);
    res.status(500).json({ error: "Server error" });
  }
});

app.post("/cancel-order/:orderId", async (req, res) => {
  const { orderId } = req.params;
  if (!orderId) {
    return res.status(400).json({ err: "Invalid Payload" });
  }
  const client = await pool.connect();
  try {
    await client.query("BEGIN");
    // 1️⃣ Check if order exists
    const orderRes = await client.query("SELECT * FROM orders WHERE id = $1", [
      orderId,
    ]);

    if (orderRes.rows.length === 0) {
      throw new Error("Order not found");
    }
    const order = orderRes.rows[0];

    // 2️⃣ Prevent duplicate cancel
    if (order.status === "cancelled") {
      throw new Error("Order already cancelled");
    }

    if (order.status === "completed") {
      throw new Error("Completed order cannot be cancelled");
    }

    // 3️⃣ Get order items
    const itemsRes = await client.query(
      "SELECT * FROM order_items WHERE order_id = $1",
      [orderId],
    );

    const items = itemsRes.rows;

    // 4️⃣ Restore inventory
    for (const item of items) {
      await client.query(
        `
        UPDATE inventory
        SET stock_count = stock_count + $1
        WHERE id = $2
        `,
        [item.quantity, item.product_id],
      );
    }

    // 5️⃣ Update order status
    await client.query(
      `
      UPDATE orders
      SET status = 'cancelled'
      WHERE id = $1
      `,
      [orderId],
    );

    await client.query("COMMIT");

    res.json({
      message: "Order cancelled successfully",
    });
  } catch (err) {
    await client.query("ROLLBACK");
    console.error(err);
    res.status(500).json({ error: err.message });
  } finally {
    client.release();
  }
});

app.post("/complete-order/:orderId", async (req, res) => {
  const { orderId } = req.params;
  const { items } = req.body;

  if (!orderId) {
    return res.status(400).json({ error: "OrderId is required" });
  }

  const client = await pool.connect();

  try {
    await client.query("BEGIN");

    // ✅ CASE 1: No items → simple status update
    if (!items || items.length === 0) {
      const result = await client.query(
        `UPDATE orders
         SET status = 'picked_up'
         WHERE id = $1 AND status != 'cancelled'
         RETURNING *`,
        [orderId],
      );

      if (result.rowCount === 0) {
        throw new Error("Order not found or cannot be completed");
      }

      await client.query("COMMIT");
      return res.status(200).json({
        message: "Order completed successfully",
        order: result.rows[0],
      });
    }

    // ✅ CASE 2: Items exist → diff logic

    // 1. Get existing items
    const existingRes = await client.query(
      `SELECT product_id, quantity FROM order_items WHERE order_id = $1`,
      [orderId],
    );

    const existingMap = new Map();
    existingRes.rows.forEach((item) => {
      existingMap.set(item.product_id, item.quantity);
    });

    let totalPrice = 0;

    // 2. Process incoming items
    for (const item of items) {
      const oldQty = existingMap.get(item.product_id) || 0;
      const newQty = item.quantity;
      const diff = newQty - oldQty;

      // 🔒 Lock product row
      const productRes = await client.query(
        `SELECT price, stock_count FROM inventory WHERE id = $1 FOR UPDATE`,
        [item.product_id],
      );

      if (productRes.rowCount === 0) {
        throw new Error(`Product ${item.product_id} not found`);
      }

      const product = productRes.rows[0];

      // 🔥 Apply diff to inventory
      if (diff > 0) {
        // increase order → decrease stock
        if (product.stock_count < diff) {
          throw new Error(`Insufficient stock for product ${item.product_id}`);
        }

        await client.query(
          `UPDATE inventory
           SET stock_count = stock_count - $1
           WHERE id = $2`,
          [diff, item.product_id],
        );
      } else if (diff < 0) {
        // decrease order → increase stock
        await client.query(
          `UPDATE inventory
           SET stock_count = stock_count + $1
           WHERE id = $2`,
          [Math.abs(diff), item.product_id],
        );
      }

      // 🔁 Update order_items (no delete/insert chaos)
      if (oldQty === 0) {
        await client.query(
          `INSERT INTO order_items (order_id, product_id, quantity, price)
           VALUES ($1, $2, $3, $4)`,
          [orderId, item.product_id, newQty, product.price],
        );
      } else {
        await client.query(
          `UPDATE order_items
           SET quantity = $1
           WHERE order_id = $2 AND product_id = $3`,
          [newQty, orderId, item.product_id],
        );
      }

      // accumulate price
      totalPrice += product.price * diff;

      existingMap.delete(item.product_id);
    }

    // 4. Update order
    await client.query(
      `UPDATE orders
       SET total_amount = total_amount + $1,
           status = 'picked_up'
       WHERE id = $2`,
      [totalPrice, orderId],
    );

    await client.query("COMMIT");

    res.status(200).json({
      message: "Order updated & completed successfully",
    });
  } catch (err) {
    await client.query("ROLLBACK");
    console.error(err);

    res.status(500).json({
      error: err.message || "Something went wrong",
    });
  } finally {
    client.release();
  }
});

app.get("/get-user-orders/:userId", async (req, res) => {
  console.log("req.body", req.params);
  const { userId } = req.params;
  if (!userId) throw new Error("USERID missing");
  try {
    const query = `
      SELECT 
        o.id AS order_id,
        o.customer_name,
        o.email,
        o.phone,
        o.status,
        o.total_amount,
        o.created_at,

        oi.product_id,
        oi.quantity,

        i.item_name,
        i.image_url,
        i.price

      FROM orders o
      JOIN order_items oi ON o.id = oi.order_id
      JOIN inventory i ON oi.product_id = i.id

      WHERE o.user_name = $1
    `;

    const result = await pool.query(query, [userId]);

    if (result.rows.length === 0) {
      return res.status(200).json({ message: "No Orders found" });
    }
    const data = result.rows;

    const ordersMap = {};

    for (const row of result.rows) {
      if (!ordersMap[row.order_id]) {
        ordersMap[row.order_id] = {
          order_id: row.order_id,
          customer_name: row.customer_name,
          email: row.email,
          phone: row.phone,
          status: row.status,
          total_amount: row.total_amount,
          created_at: row.created_at,
          items: [],
        };
      }

      ordersMap[row.order_id].items.push({
        product_id: row.product_id,
        item_name: row.item_name,
        image_url: row.image_url,
        price: row.price,
        quantity: row.quantity,
      });
    }

    // convert object → array
    const orders = Object.values(ordersMap);

    res.json(orders);
  } catch (err) {
    console.error("Error fetching order details:", err.message);
    res.status(500).json({ error: "Server error" });
  }
});

app.get("/notify-requests", async (req, res) => {
  const query =
    "SELECT n.status, n.email, i.item_name,n.created_at from notify_requests n join inventory i on i.id = n.product_id where status='pending' ";
  try {
    const result = await pool.query(query);
    return res.json(result.rows);
  } catch (error) {
    console.error("Error fetching notify requests", error);
  }
});

// app.listen(PORT, () => {
//   console.log("Server started running at port");
// });

server.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});
